patch: support multiple patch paths or dirs
tableauio/loader pull request #67
Opened 2024-10-12 03:21 UTC by Kybxd

relevant to https://github.com/tableauio/tableau/pull/156

2024-10-12 09:49 UTC, wenchy requested changes

2024-10-12 09:49 UTC, wenchy commented on cmd/protoc-gen-cpp-tableau-loader/embed/hub.pc.h
> +  std::vector<std::string> patch_dirs;
`PatchPaths` -> `Patch paths`
`PatchDirs` -> `Patch dirs`

2024-10-12 09:49 UTC, wenchy commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +#define ATOM_PRINT_MAP(m)                                                                  \
`ATOM_PRINT_VECTOR` -> `ATOM_VECTOR_STR`
`ATOM_PRINT_MAP` -> `ATOM_MAP_STR`

2024-10-12 09:49 UTC, wenchy commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +template <typename DataStructure>
`DataStructure` -> `T`

2024-10-12 09:49 UTC, wenchy commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +    ss << "{" << it->first << ", " << it->second << "}";                                   \
`,` -> `: `

2024-10-14 02:59 UTC, Kybxd commented on cmd/protoc-gen-cpp-tableau-loader/embed/hub.pc.h
> +  std::vector<std::string> patch_dirs;
done

2024-10-14 02:59 UTC, Kybxd commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +#define ATOM_PRINT_MAP(m)                                                                  \
done

2024-10-14 03:01 UTC, Kybxd commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +template <typename DataStructure>
done

2024-10-14 03:01 UTC, Kybxd commented on cmd/protoc-gen-cpp-tableau-loader/embed/logger.pc.h
> +    ss << "{" << it->first << ", " << it->second << "}";                                   \
done

2024-10-14 03:56 UTC, wenchy approved these changes

2024-10-14 03:56 UTC, merged